export enum SCOPES {
  ROOT = 'ROOT',
  REGISTER_ACCOUNTS = 'REGISTER_ACCOUNTS',
  AUTHENTICATE_USERS = 'AUTHENTICATE_USERS',
}

export enum TOKEN_TYPES {
  ACCESS = 'ACCESS',
  REFRESH = 'REFRESH',
  CONFIRMATION = 'CONFIRMATION',
  RESET = 'RESET',
}

export enum TEMPLATES {
  CONFIRM_EMAIL = 'confirmation',
}

export enum CONFIRM_EMAIL_STATUS {
  ALREADY_CONFIRMED = ' ALREADY_CONFIRMED',
  EXPIRED = 'EXPIRED',
  INVALID = 'INVALID',
  SUCCESS = 'SUCCESS',
}
