export enum SCOPES {
  ROOT = 'ROOT',
  REGISTER_ACCOUNTS = 'REGISTER_ACCOUNTS',
  AUTHENTICATE_USERS = 'AUTHENTICATE_USERS',
}

export enum TOKEN_TYPES {
  ACCESS = 'ACCESS',
  REFRESH = 'REFRESH',
  CONFIRMATION = 'CONFIRMATION',
  RESET = 'RESET',
}
