name: CI

on:
  push:
    branches:
      - 'develop'

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  ci-publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: yarn

      - run: yarn --frozen-lockfile --ignore-scripts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - run: sudo ln -s /usr/bin/nodejs /usr/bin/node
      - run: yarn generate-types

      - uses: nrwl/nx-set-shas@v3
      - run: INPUT_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} yarn nx affected --base=$NX_BASE --head=$NX_HEAD -t container -c development --skip-nx-cache
